services:
  sandbox:
    build: ./sandbox
    image: tanuki-sandbox
  runner:
    build: ./runner
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLAG=flag{tanuki_should_be_in_the_zodiac_c7cfe870}