name: chal
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  dart_jsonwebtoken: ^2.12.0
  js: ^0.6.7
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  webdev: ^3.0.7+1
